# Grafana Data Sources Configuration
# Configuración de fuentes de datos para Grafana

apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    editable: true
    jsonData:
      httpMethod: POST
      queryTimeout: 60s
      timeInterval: 15s

  - name: PostgreSQL
    type: postgres
    access: proxy
    url: postgresql-db:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: postgres123
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 15
      timescaledb: false

  - name: PostgreSQL Replica
    type: postgres
    access: proxy
    url: postgresql-replica:5432
    database: postgres
    user: postgres
    secureJsonData:
      password: postgres123
    jsonData:
      sslmode: disable
      maxOpenConns: 0
      maxIdleConns: 2
      connMaxLifetime: 14400
      postgresVersion: 15
      timescaledb: false
