# Prometheus Configuration
# Configuración de Prometheus para monitoreo de PostgreSQL

global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'postgresql-docker'
    replica: 'prometheus-1'

rule_files:
  - "rules/*.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 5s
    metrics_path: /metrics

  # PostgreSQL Exporter
  - job_name: 'postgresql'
    static_configs:
      - targets: ['postgresql-exporter:9187']
    scrape_interval: 10s
    metrics_path: /metrics
    params:
      format: ['prometheus']

  # Node Exporter (if enabled)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 10s
    metrics_path: /metrics

  # cAdvisor (if enabled)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
    scrape_interval: 10s
    metrics_path: /metrics

  # Docker containers
  - job_name: 'docker'
    static_configs:
      - targets: ['docker-exporter:9323']
    scrape_interval: 10s
    metrics_path: /metrics

  # PostgreSQL Replica (if enabled)
  - job_name: 'postgresql-replica'
    static_configs:
      - targets: ['postgresql-replica-exporter:9188']
    scrape_interval: 10s
    metrics_path: /metrics
    params:
      format: ['prometheus']
